/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author luddelandstrom
 */
public class AliensNara extends javax.swing.JFrame {

    private InfDB idb;
    private String valdPlats;
    private ArrayList<HashMap<String, String>> resultat;
    private ArrayList<HashMap<String, String>> svar;
    private User user;

    /**
     * Creates new form AliensNara
     */
    public AliensNara(InfDB idb, User user) {
        initComponents();
        this.idb = idb;
        this.user = user;
        
        fyllrutan();
    }

    private void jcbNYActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
    }
    
    private void fyllrutan(){
        jTArea.setText("");

        ArrayList<HashMap<String, String>> soktaAliens;

        try {

            String ufraga = "SELECT plats.Benamning from plats join alien on plats.Plats_ID = alien.Plats where alien.Namn = '" + user.getUsername() + "'";
             
            String uplats = idb.fetchSingle(ufraga);
            
            String fraga = "SELECT * from alien join plats on plats_ID = plats where benamning='" + uplats + "'";
            soktaAliens = idb.fetchRows(fraga);
            

            for (HashMap<String, String> alien : soktaAliens) {
                jTArea.append(" " + alien.get("Namn") + "\t");
                jTArea.append(" " + alien.get("Telefon") + "\n");
                
            }
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt meddelande" + ettUndantag.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTArea = new javax.swing.JTextArea();
        jButClose1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Aliens i ditt område");

        jTArea.setColumns(20);
        jTArea.setRows(5);
        jScrollPane1.setViewportView(jTArea);

        jButClose1.setText("Close");
        jButClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButClose1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Namn och Telefonnummer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButClose1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButClose1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButClose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButClose1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButClose1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTArea;
    // End of variables declaration//GEN-END:variables
}
