/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenInBlack;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;


        

/**
 *
 * @author luddelandstrom
 */
public class AlienSida extends javax.swing.JFrame {

    private AliensNaraDig aliensNara;
    private static InfDB idb;
    
    
    
    /**
     * Creates new form AlienSida
     */
    public AlienSida(InfDB idb) {
        initComponents();
        this.idb = idb;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HuvudText = new javax.swing.JLabel();
        Valkommen = new javax.swing.JLabel();
        AndraLosen = new javax.swing.JButton();
        AlienNara = new javax.swing.JButton();
        KontaktaOmradesChef = new javax.swing.JButton();
        OmradesChefInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HuvudText.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        HuvudText.setText("AlienSida");

        Valkommen.setText(" Välkommen");

        AndraLosen.setText("Ändra lösen");
        AndraLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraLosenActionPerformed(evt);
            }
        });

        AlienNara.setText("Aliens nära dig");
        AlienNara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlienNaraActionPerformed(evt);
            }
        });

        KontaktaOmradesChef.setText("Kontakta områdeschef");

        OmradesChefInfo.setText("jTextField1");
        OmradesChefInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OmradesChefInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KontaktaOmradesChef))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AndraLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AlienNara, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Valkommen)
                            .addComponent(OmradesChefInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(HuvudText)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(HuvudText)
                .addGap(43, 43, 43)
                .addComponent(Valkommen)
                .addGap(18, 18, 18)
                .addComponent(OmradesChefInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(AlienNara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KontaktaOmradesChef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AndraLosen)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AndraLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraLosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AndraLosenActionPerformed

    
    
    private void AlienNaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlienNaraActionPerformed
        aliensNara = new AliensNaraDig();
        aliensNara.setVisible(true);
    }//GEN-LAST:event_AlienNaraActionPerformed

    //Skriver ut infomration om OmrådesChefen
    private void OmradesChefInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OmradesChefInfoActionPerformed
        // hämta områdeschef
        try
        {
            
           String fraga = "select agent.namn, agent.Telefon, agent.Agent_ID, omradeschef.Omrade\n" +
            "from agent\n" +
            "join omradeschef on agent.Agent_ID = omradeschef.Agent_ID\n" +
            "join omrade on omradeschef.Omrade = omrade.Omrades_ID\n" +
            "where agent.agent_id =";
           String svar = idb.fetchSingle(fraga);
           String resultat = fraga;
           OmradesChefInfo.setText(resultat);
            
        }
        catch(InfException e)
        {
            JOptionPane.showMessageDialog(null, );
            
            
            
        }
        //skriva ut namn, telefon, område
        
    }//GEN-LAST:event_OmradesChefInfoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlienSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlienSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlienSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlienSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlienSida(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlienNara;
    private javax.swing.JButton AndraLosen;
    private javax.swing.JLabel HuvudText;
    private javax.swing.JButton KontaktaOmradesChef;
    private javax.swing.JTextField OmradesChefInfo;
    private javax.swing.JLabel Valkommen;
    // End of variables declaration//GEN-END:variables
}
