/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author luddelandstrom
 */
public class AliensNara extends javax.swing.JFrame {

    //fält för aliensNara
    private InfDB idb;
    private String valdPlats;
    private ArrayList<HashMap<String, String>> resultat;
    private ArrayList<HashMap<String, String>> svar;
    private User user;

    /**
     * Creates new form AliensNara
     */
    public AliensNara(InfDB idb, User user) {
        initComponents();
        this.idb = idb;
        this.user = user;
        
        fyllrutan();
        jTtextomrade.setEditable(false);
    }

    private void jcbNYActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
    }
    
    //Tar fram information om aliens som befinner sig i sitt område.
    private void fyllrutan(){
        jTtextomrade.setText("");

        ArrayList<HashMap<String, String>> soktaAliens;

        try {

            String ufraga = "SELECT plats.Benamning from plats join alien on plats.Plats_ID = alien.Plats where alien.Namn = '" + user.getUsername() + "'";

            String uplats = idb.fetchSingle(ufraga);

            String fraga = "SELECT * from alien join plats on plats_ID = plats where benamning='" + uplats + "'";
            soktaAliens = idb.fetchRows(fraga);

            for (HashMap<String, String> alien : soktaAliens) {
                jTtextomrade.append(" " + alien.get("Namn") + "\t");
                jTtextomrade.append(" " + alien.get("Telefon") + "\n");

            }
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt meddelande" + ettUndantag.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitel = new javax.swing.JLabel();
        jSPtext = new javax.swing.JScrollPane();
        jTtextomrade = new javax.swing.JTextArea();
        jBClose = new javax.swing.JButton();
        jLBeskrivning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLTitel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLTitel.setText("Aliens i ditt område");

        jTtextomrade.setColumns(20);
        jTtextomrade.setRows(5);
        jSPtext.setViewportView(jTtextomrade);

        jBClose.setText("Stäng");
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });

        jLBeskrivning.setText("Namn och Telefonnummer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLTitel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jBClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBeskrivning)
                            .addComponent(jSPtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLTitel)
                .addGap(35, 35, 35)
                .addComponent(jLBeskrivning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBClose)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JLabel jLBeskrivning;
    private javax.swing.JLabel jLTitel;
    private javax.swing.JScrollPane jSPtext;
    private javax.swing.JTextArea jTtextomrade;
    // End of variables declaration//GEN-END:variables
}
