package meninblack;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author emanuelgotesjo
 */

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

public class Inlog extends javax.swing.JFrame {

    private InfDB idb;
    private String svar;
    private String resultat;
    private boolean inloggad;
    private String vald; 
    private String alienSvar;
    private String alienResultat;
    
    private User user;
    

    

    
    /**
     * Creates new form Inlog
     */
    public Inlog(InfDB idb) {
        initComponents();
        this.idb = idb;
        
        inloggad = false;
        svar = " ";
        resultat = " ";
        vald = " ";
        alienSvar = " ";
        alienResultat = " ";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLTitel = new javax.swing.JLabel();
        txtbUserName = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jBLoggaIN = new javax.swing.JButton();
        jCtyp = new javax.swing.JComboBox<>();
        txtbLosenord = new javax.swing.JPasswordField();
        jLUser = new javax.swing.JLabel();
        jLpic = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLTitel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLTitel.setText("Inloggning");

        txtbUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbUserNameActionPerformed(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        userLabel.setText("Användarnamn:");

        passwordLabel.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        passwordLabel.setText("Lösenord:");

        jBLoggaIN.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jBLoggaIN.setText("Logga in");
        jBLoggaIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoggaINActionPerformed(evt);
            }
        });

        jCtyp.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jCtyp.setMaximumRowCount(2);
        jCtyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agent", "Alien" }));
        jCtyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtypActionPerformed(evt);
            }
        });

        txtbLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbLosenordActionPerformed(evt);
            }
        });

        jLUser.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLUser.setText("Användare:");
        jLUser.setMaximumSize(new java.awt.Dimension(80, 16));

        jLpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meninblack/1283126.png"))); // NOI18N
        jLpic.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(userLabel)
                            .addComponent(txtbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(265, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCtyp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jLpic, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLTitel)
                        .addGap(23, 23, 23)
                        .addComponent(jBLoggaIN)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLTitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCtyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLpic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLoggaIN)
                    .addComponent(txtbLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbUserNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtbUserNameActionPerformed

    private void jCtypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtypActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtypActionPerformed
  
    private void txtbLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbLosenordActionPerformed

    
    
    
    /**
     *
     *
     * Denna metod för knappen 'Logga in' hämtar metoden KollaLosenord() först
     * och checkar även om booleanen 'inloggad' är true. Om true uppnås skapas
     * en ny agentsida, vilket för användaren blir att om man skriver in rätt
     * lösernord för rätt Agent tar systemet användaren till platsen Agentsida.
     * Om det är false får användaren även ett meddelande att lösenordet är fel.
     *
     * @param evt
     */
    private void jBLoggaINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoggaINActionPerformed

        checkaComboBox();
        if (vald.equals("Agent") && kollaAgentLosenord()) {

            user = new User(idb, txtbUserName.getText());

            new Agentsida(idb, user).setVisible(true);
            dispose();

        } else if (vald.equals("Alien") && kollaAlienLosenord()) {

            user = new User(idb, txtbUserName.getText());

            new AlienSida(idb, user).setVisible(true);
            dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Fel lösenord. Pröva ett annat");
    }//GEN-LAST:event_jBLoggaINActionPerformed
    }
    
    
    /**
     * Metoden ställer en SQL fråga till databasen där den tar namn lösenordet från agenten där namnet
     * är lika med användarnamnet som användaren skriver in i textrutan. Med två olika Exceptions
     * fångar vi även upp och skickar ett meddelande om antingen användarnamnet är fel eller lösenordet.
     * Metoden kollar till slut om resultaten från SQL frågan är lika med inputen i lösenords-rutan, 
     * vilket ändrar värdet på booleanen 'inloggad' till true om så är fallet. 
     */ 
    private boolean kollaAgentLosenord() {
        inloggad = false;
        String anvandarnamn = txtbUserName.getText();
        
        if (Validering.isNamnGodkant(anvandarnamn)) {
            try {
                
                String fraga = "Select losenord from agent where namn='" + anvandarnamn + "'";
                svar = idb.fetchSingle(fraga);
                resultat = svar;

            } catch (InfException E) {
                JOptionPane.showMessageDialog(null, "Fel");
                System.out.println("Internt Felmeddelande" + E.getMessage());
            } catch (Exception Undantag) {
                JOptionPane.showMessageDialog(null, "Kunde inte hämta lösenord för denna Agent");
                System.out.println("Internt Felmeddelande" + Undantag.getMessage());
            }

            if (resultat == null) {
                inloggad = false;
            } else if (resultat.equals(txtbLosenord.getText())) {
                inloggad = true;
            }
        }

        return inloggad;

    }
    
    
    
    
    private boolean kollaAlienLosenord() {
        inloggad = false;
        String alienNamn = txtbUserName.getText();

        if (Validering.isNamnGodkant(alienNamn)) {
            try {
                
                String alienFraga = "select losenord from alien where namn ='" + alienNamn + "'";
                alienSvar = idb.fetchSingle(alienFraga);
                alienResultat = alienSvar;

            } catch (InfException Ex) {
                JOptionPane.showMessageDialog(null, "Fel");
                System.out.println("Internt Felmeddelande" + Ex.getMessage());
            } catch (Exception EUndantag) {
                JOptionPane.showMessageDialog(null, "Fel, pröva igen");
            }

            if (alienResultat == null) {
                inloggad = false;
            } else if (alienResultat.equals(txtbLosenord.getText())) {
                inloggad = true;
            }
        }
        
        return inloggad;
    }
    

    
    private void checkaComboBox() {
        vald = jCtyp.getSelectedItem().toString();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLoggaIN;
    private javax.swing.JComboBox<String> jCtyp;
    private javax.swing.JLabel jLTitel;
    private javax.swing.JLabel jLUser;
    private javax.swing.JLabel jLpic;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField txtbLosenord;
    private javax.swing.JTextField txtbUserName;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
