/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.util.ArrayList;
import java.util.Calendar;
import oru.inf.InfDB;

/**
 *
 * @author emanuelgotesjo
 */
public class RegistreraFordon extends javax.swing.JFrame {
    
    //Klassens fält
    InfDB idb;

    /**
     * Creates new form RegistreraFordon
     */
    public RegistreraFordon(InfDB idb) {  
             
        initComponents();
        
       this.idb = idb;
       fyllComboBoxen();
                
                
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLTitel = new javax.swing.JLabel();
        jTFordonID = new javax.swing.JTextField();
        jTBeskrivning = new javax.swing.JTextField();
        jComBYear = new javax.swing.JComboBox<>();
        jLarsModell = new javax.swing.JLabel();
        jBLaggTill = new javax.swing.JButton();
        dateChooser1 = new com.raven.datechooser.DateChooser();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitel.setText("Registrera Fordon");

        jTFordonID.setText("Fordons ID");
        jTFordonID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFordonIDMousePressed(evt);
            }
        });

        jTBeskrivning.setText("Fordonsbeskrivning");
        jTBeskrivning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTBeskrivningMousePressed(evt);
            }
        });
        jTBeskrivning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBeskrivningActionPerformed(evt);
            }
        });

        jComBYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComBYearActionPerformed(evt);
            }
        });

        jLarsModell.setText("Årsmodell");

        jBLaggTill.setText("Lägg till");
        jBLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLaggTillActionPerformed(evt);
            }
        });

        dateChooser1.setDateFormat("yyyy-MM-dd");

        jLabel1.setText("Registreringsdatum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBLaggTill)
                    .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComBYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTBeskrivning)
                    .addComponent(jTFordonID)
                    .addComponent(jLTitel)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLarsModell)))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLTitel)
                .addGap(18, 18, 18)
                .addComponent(jTFordonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLarsModell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBLaggTill)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComBYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComBYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComBYearActionPerformed

    // Tömmer FordonsID första gången man ska börja skriva
    private void jTFordonIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFordonIDMousePressed

        if (jTFordonID.getText().equals("Fordons ID")) {
            jTFordonID.setText("");
        }
    }//GEN-LAST:event_jTFordonIDMousePressed

    // Tömmer Beskrivningsrutan första gången man ska börja skriva
    private void jTBeskrivningMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBeskrivningMousePressed

        if (jTBeskrivning.getText().equals("Fordonsbeskrivning")) {
            jTBeskrivning.setText("");
        }
    }//GEN-LAST:event_jTBeskrivningMousePressed

    private void jTBeskrivningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBeskrivningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBeskrivningActionPerformed

    //Lägger till ett fordon i registret
    private void jBLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLaggTillActionPerformed
     
     String fID = jTFordonID.getText();
     String fbenmn = jTBeskrivning.getText();
     int arsmodell = Integer.parseInt(jComBYear.getSelectedItem().toString());
     String regDate = dateChooser1.getDateFormat();
     
     // Checka så att ID är ifyllt och
     
     String sqlFraga = "INSERT INTO mibdb.fordon (Fordons_ID, Fordonsbeskrivning, Registreringsdatum, Arsmodell) VALUES ('"+fID+"', '"+fbenmn+"', '"+regDate+"', "+arsmodell+")";
        
    }//GEN-LAST:event_jBLaggTillActionPerformed

    //Fyller komboboxen med årtal från 1950 fram till idag
    private void  fyllComboBoxen(){
        
        //Skapar en arrayList innehållande alla årtal
        ArrayList<String> years_tmp = new ArrayList<>();
        for(int years = 1950; years<=Calendar.getInstance().get(Calendar.YEAR); years++) {
        years_tmp.add(years+""); 
        }
        
        //Lägger till åren i comboboxen
        for(String aYear : years_tmp) {
            jComBYear.addItem(aYear);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jBLaggTill;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComBYear;
    private javax.swing.JLabel jLTitel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLarsModell;
    private javax.swing.JTextField jTBeskrivning;
    private javax.swing.JTextField jTFordonID;
    // End of variables declaration//GEN-END:variables
}
