/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meninblack;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Marti
 */
public class SokAgent extends javax.swing.JFrame {
    private static InfDB idb;
    private String agentNamn;
    private int pid;
    

    /**
     * Creates new form SokAgent
     */
    public SokAgent(InfDB idb, String agentNamn) {
        initComponents();
        this.idb = idb;
        this.agentNamn = agentNamn;
        fyllInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLNamnAgent = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLNummerAgent = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLDatumAgent = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLAnsvarigAgent = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLStatusAgent = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTDate = new javax.swing.JTextField();
        jBStang = new javax.swing.JButton();

        dateChooser1.setDateFormat("yyyy-MM-dd");
        dateChooser1.setTextRefernce(jTDate);

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel1.setText("Info om Agent");

        jLabel2.setText("Namn");

        jLNamnAgent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLNamnAgent.setText("jLnamn");

        jLabel4.setText("Telefon");

        jLNummerAgent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLNummerAgent.setText("Nummer");

        jLabel6.setText("Anställningsdatum");

        jLDatumAgent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLDatumAgent.setText("Datum");

        jLabel8.setText("Område");

        jLAnsvarigAgent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLAnsvarigAgent.setText("Ansvarig i");

        jLabel10.setText("AdminStatus");

        jLStatusAgent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLStatusAgent.setText("Status :");

        jButton1.setText("Ändra Namn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Ändra Datum");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ändra Område");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Ändra Nummer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBStang.setText("Stäng");
        jBStang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBStangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNamnAgent)
                    .addComponent(jLNummerAgent)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLDatumAgent)
                    .addComponent(jLStatusAgent)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLAnsvarigAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jTDate))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jBStang))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNamnAgent)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNummerAgent)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLDatumAgent)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLAnsvarigAgent))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(28, 28, 28)
                                .addComponent(jButton4)))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLStatusAgent)
                .addGap(9, 9, 9)
                .addComponent(jBStang)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Denna metod ändrar ett namn i agenttabellen till det användaren väljer. Det finns en validering för att se om agenten
        // i fråga finns med i databasen, och då gör en uppdatering på tabellen. Samt efter varje metod görs en åtkomst för att 
        // fylla informationen igen. Detta är för att sidan ska uppdateras direkt med den nya informationen som finns i databasen. 
        String nuvarandeNamn = agentNamn;
        String nyttNamn = JOptionPane.showInputDialog("Vad ska agenten få för nytt namn?\nNamnet måste vara unikt");

        if (!Validering.finnsUsernameiDB(nyttNamn));
        {
            try {
                idb.update("UPDATE agent SET namn= '" + nyttNamn + "' where namn like '" + nuvarandeNamn + "'");

                if (Validering.finnsUsernameiDB(nyttNamn)) {
                    agentNamn = nyttNamn;
                }
            } catch (InfException ettUndantag) {
                JOptionPane.showMessageDialog(null, "DATABASFEL");
                System.out.println("Internt meddelande" + ettUndantag.getMessage());
            }
            // Uppdaterar sidan med den infon du valt. 
            fyllInformation();
    }//GEN-LAST:event_jButton1ActionPerformed
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Denna metod tar in en input på vad det nya anställningsdatumet skall vara.
        // Sedan uppdaterar den databasen med den information användaren skrev in.
        String nyttDatum = jTDate.getText();
        

            try {
                idb.update("UPDATE Agent SET Anstallningsdatum = '"+nyttDatum+"' where namn like '" + agentNamn + "'");
            } catch (InfException ettUndantag) {
                JOptionPane.showMessageDialog(null, "Detta datum kunde ej uppdateras");
                System.out.println("Ett fel uppstod med databasen" + ettUndantag.getMessage());
 
        }
        fyllInformation();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Vad denna metod gör är att först tar en SQL fråga som tar benämningen från område tabellen, och gör den till
        // en arraylista. 
        String nyttOmråde = "SELECT benamning from omrade";
        ArrayList<String> omradeArrayList = new ArrayList<>();
        int nyPlats = 0;

        try {
            omradeArrayList = idb.fetchColumn(nyttOmråde);
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Ett fel uppstod med databasen");
            System.out.println("Internt felmedellande" + ettUndantag);
        }
        Object[] omradeArray = omradeArrayList.toArray();
        String valtOmrade = (String) JOptionPane.showInputDialog(null, "På vilken ny plats ska agenten arbeta i?", "Välj plats..", JOptionPane.QUESTION_MESSAGE, null, omradeArray, omradeArray[0]);

        try {
            String platsNamn = valtOmrade;
            String platsIDFraga = "SELECT Omrades_ID FROM omrade WHERE benamning ='" + platsNamn + "'";

            String charPlats = idb.fetchSingle(platsIDFraga);

            nyPlats = Integer.parseInt(charPlats);
        } catch (InfException ettE) {
            JOptionPane.showMessageDialog(null, "platsen finns ej med i databasen. Vänligen pröva ett annat");
            System.out.println("Internt fel" + ettE.getMessage());
        }
        try {
            idb.update("Update agent SET omrade ='" + nyPlats + "' where namn ='" + agentNamn + "'");
        } catch (InfException ettE) {
            JOptionPane.showMessageDialog(null, "Kunde inte uppdatera området");
            System.out.println("Internt fel" + ettE.getMessage());
        }
        // Uppdaterar sidan med det nya området.
        fyllInformation();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Denna metod ändrar numret för en agent med hjälp av en parameter som använderen själv får skriva in. 
        // Med variabeln som lagrar informationen som användaren skriver in kan koden göra en update där villkoret 
        // blir vad agenten heter, så rätt nummer kopplas till rätt agent. 
        String nyttNummer = JOptionPane.showInputDialog("Vad ska det nya numret vara?");
       
        try {
            idb.update("UPDATE agent SET Telefon='" + nyttNummer + "' where namn like '" + agentNamn + "'");
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Detta nummer kunde inte uppdateras");
            System.out.println("Fel när numret skulle uppdateras" + ettUndantag.getMessage());
        }
        // Uppdaterar sidan med det nya numret.
        fyllInformation();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBStangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBStangActionPerformed
        //Stänger fönstret
        dispose();
    }//GEN-LAST:event_jBStangActionPerformed




    /**
     * Fyller Fönstret med information
     * @param 
     */
    private void fyllInformation() {
      
       
        jLNamnAgent.setText(agentNamn);
        
        try {
            jLNummerAgent.setText(idb.fetchSingle("Select telefon from agent where namn ='" + agentNamn + "'"));
            jLDatumAgent.setText(idb.fetchSingle("Select anstallningsdatum from agent where namn ='" + agentNamn + "'"));
            jLAnsvarigAgent.setText(idb.fetchSingle("select plats.`Benamning` from plats join omrade on omrade.`Omrades_ID` = Finns_I join agent on omrade = omrade.`Omrades_ID` where namn ='" + agentNamn + "'"));
            jLStatusAgent.setText(idb.fetchSingle("Select administrator from agent where namn ='" + agentNamn + "'"));
            
            //hämtar Alien_ID från databasen
            String CharID = idb.fetchSingle("select Agent_ID from agent where namn ='" + agentNamn + "'");
            pid = Integer.parseInt(CharID);
        } catch(InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel med databasen");
            System.out.println("internt meddelande" + ettUndantag.getMessage());
        }
        if(jLStatusAgent.equals("J")) {
            jLStatusAgent.setText("Är administratör");
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jBStang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLAnsvarigAgent;
    private javax.swing.JLabel jLDatumAgent;
    private javax.swing.JLabel jLNamnAgent;
    private javax.swing.JLabel jLNummerAgent;
    private javax.swing.JLabel jLStatusAgent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTDate;
    // End of variables declaration//GEN-END:variables
}